/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Sarabun', 'Sarabun Fallback', 'Inter', 'system-ui', 'sans-serif'],
      },
      colors: {
        amber: {
          50:  '#fffbeb',
          100: '#fef3c7',
          200: '#fde68a',
          300: '#fcd34d',
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
          700: '#b45309',
          800: '#92400e',
          900: '#78350f',
        },
      },
      typography: ({ theme }) => ({
        stone: {
          css: {
            '--tw-prose-body':        theme('colors.stone[700]'),
            '--tw-prose-headings':    theme('colors.stone[900]'),
            '--tw-prose-links':       theme('colors.amber[700]'),
            '--tw-prose-bold':        theme('colors.stone[900]'),
            '--tw-prose-counters':    theme('colors.stone[500]'),
            '--tw-prose-bullets':     theme('colors.stone[400]'),
            '--tw-prose-hr':          theme('colors.stone[200]'),
            '--tw-prose-quotes':      theme('colors.stone[700]'),
            '--tw-prose-quote-borders': theme('colors.amber[300]'),
            '--tw-prose-captions':    theme('colors.stone[500]'),
            '--tw-prose-code':        theme('colors.stone[800]'),
            '--tw-prose-pre-code':    theme('colors.stone[200]'),
            '--tw-prose-pre-bg':      theme('colors.stone[800]'),
            '--tw-prose-th-borders':  theme('colors.stone[300]'),
            '--tw-prose-td-borders':  theme('colors.stone[200]'),
            '--tw-prose-invert-body':        theme('colors.stone[300]'),
            '--tw-prose-invert-headings':    theme('colors.stone[100]'),
            '--tw-prose-invert-links':       theme('colors.amber[400]'),
            '--tw-prose-invert-bold':        theme('colors.stone[100]'),
            '--tw-prose-invert-counters':    theme('colors.stone[400]'),
            '--tw-prose-invert-bullets':     theme('colors.stone[600]'),
            '--tw-prose-invert-hr':          theme('colors.stone[700]'),
            '--tw-prose-invert-quotes':      theme('colors.stone[300]'),
            '--tw-prose-invert-quote-borders': theme('colors.amber[600]'),
            '--tw-prose-invert-captions':    theme('colors.stone[400]'),
            '--tw-prose-invert-code':        theme('colors.stone[200]'),
            '--tw-prose-invert-pre-code':    theme('colors.stone[200]'),
            '--tw-prose-invert-pre-bg':      theme('colors.stone[900]'),
            '--tw-prose-invert-th-borders':  theme('colors.stone[600]'),
            '--tw-prose-invert-td-borders':  theme('colors.stone[700]'),
          },
        },
      }),
    },
  },
  plugins: [require('@tailwindcss/typography')],
};
